### PR TITLE
_very_ quick fix to #4

### LINKED ISSUE #4: bug in hir type inference leading to accessing invalid index in Arena
trying to compile the following: `m::(){y:^mutx2{;y=`  results in the compiler panicking
backtrace: 

```
   0: rust_begin_unwind
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/option.rs:935:21
   4: <la_arena::map::ArenaMap<la_arena::Idx<V>,T> as core::ops::index::Index<la_arena::Idx<V>>>::index
             at /home/lena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/la-arena-0.2.1/src/map.rs:61:9
   5: hir::body::Bodies::range_for_expr
             at ./crates/hir/src/body.rs:1101:25
   6: hir_ty::ctx::<impl hir_ty::InferenceCtx>::get_mutability
             at ./crates/hir_ty/src/ctx.rs:347:33
   7: hir_ty::ctx::<impl hir_ty::InferenceCtx>::infer_stmt
             at ./crates/hir_ty/src/ctx.rs:496:28
   8: hir_ty::ctx::<impl hir_ty::InferenceCtx>::infer_expr
             at ./crates/hir_ty/src/ctx.rs:989:21
   9: hir_ty::ctx::<impl hir_ty::InferenceCtx>::finish_body_unknown
             at ./crates/hir_ty/src/ctx.rs:108:9
  10: hir_ty::ctx::<impl hir_ty::InferenceCtx>::finish_body_known
             at ./crates/hir_ty/src/ctx.rs:89:27
  11: hir_ty::InferenceCtx::get_function_signature
             at ./crates/hir_ty/src/lib.rs:383:21
  12: hir_ty::InferenceCtx::finish
             at ./crates/hir_ty/src/lib.rs:279:21
  13: capy::compile_file
             at ./crates/capy/src/main.rs:261:39
  14: capy::main
             at ./crates/capy/src/main.rs:109:5
```

### PR DESCRIPTION
**Pull request by lenawanel**
propagate None from arena indexes up to diagnostic generation

fixes #4 

also added a few #[derive(Debug)] for convenience

also looking over the commit it seems like my editor did some auto-formatting (oops), do you have a policy on formatting for this repository?

### CODE REVIEW

**Comment by NotAFlyingGoose** [comment]
The style guide is "don't make the code look ugly." My format on save was off and it looks like your editor got some things I missed.

I'm gonna look at it properly tonight, but from first glace it looks like

```
func::() {
	y : [3]usize;
	y = 0;
}
```

might also activate the bug. could you look into it?

**Comment by lenawanel** [comment]
sure @NotAFlyingGoose :D

**Comment by lenawanel** [comment]
> The style guide is "don't make the code look ugly." My format on save was off and it looks like your editor got some things I missed.
> 
> I'm gonna look at it properly tonight, but from first glace it looks like
> 
> ```
> func::() {
> 	y : [3]usize;
> 	y = 0;
> }
> ```
> 
> might also activate the bug. could you look into it?

It doesn't activate the bug, I'll try fuzzing with a fitting corpus to see if there are similar bugs.

**Comment by NotAFlyingGoose** [comment]
> It doesn't activate the bug, I'll try fuzzing with a fitting corpus to see if there are similar bugs.

Okay, something along the lines of mutation of something that doesn't have a body

**Comment by lenawanel** [comment]
> > It doesn't activate the bug, I'll try fuzzing with a fitting corpus to see if there are similar bugs.
> 
> Okay, something along the lines of mutation of something that doesn't have a body

I've been fuzzing for some time now, and this bug doesn't get triggered. 
tbf, I only used 5 seed files, and the bug is _very_ dependent on the parser's error recovery, so I think it's a better idea to wrap the ranges in options.

File: crates/hir_ty/src/ctx.rs [hunk 1]
```diff
@@ -344,7 +346,7 @@ impl InferenceCtx<'_> {
                             )
                         } else {
                             ExprMutability::ImmutableRef(
-                                current_bodies!(self).range_for_expr(local_def.value),
+                                current_bodies!(self).get_range_for_expr(local_def.value),
```
Comment (NotAFlyingGoose) [inline crates/hir_ty/src/ctx.rs:349]: I think that if the value of the local def doesn't exist, we should probably just lie and say it's mutable. An error of "you can't mutate this because it's an immutable reference" doesn't make sense because that's not the real underlying error.

Besides, a value of `ImmutableRef(None)` seems to have the same effect as `Mutable`. On line 78 they both do the same thing.

I'd probably change this whole match block to something like
```rust
match local_ty.as_pointer() {
    // Checking for bindings first makes more sense than what I wrote before
    // What do you think? A few tests would probably have to change.
    // Not really the focus of this PR though so it's wtv
    _ if !local_def.mutable => ExprMutability::ImmutableBinding(local_def.range),
    Some((mutable, _)) if assignment => {
        if mutable {
            ExprMutability::NotMutatingRefThroughDeref(
                current_bodies!(self).range_for_expr(expr),
            )
        } else if current_bodies!(self)[local_def.value] != Expr::Missing {
            ExprMutability::ImmutableRef(current_bodies!(self).range_for_expr(expr))
        } else {
            ExprMutability::Mutable
        }
    }
    _ => ExprMutability::Mutable,
}
```

Or at least something along these lines :)

**Review by NotAFlyingGoose — CHANGES_REQUESTED** [review]

File: crates/hir_ty/src/ctx.rs (hunk 1 above)
Comment (lenawanel) [reply crates/hir_ty/src/ctx.rs]: yeah, thank you

Comment (lenawanel) [reply crates/hir_ty/src/ctx.rs]: the failing tests don't seem to indicate worse diagnistics, so I will update them.

the `assign_to_immutable_ref_no_deref` test would previously output a 
`TyDiagnosticHelpKind::ImmutableRef` and now outputs a `TyDiagnosticHelpKind::ImmutableBinding`

```capy
                foo :: () {
                    bar :: 5;

                    baz :: ^bar;

                    baz = 25;
                }
```
which imo is more intuitive. 

same for the the ` assign_to_mut_ref_no_deref` test 
```capy
                foo :: () {
                    bar := 5;

                    baz :: ^mut bar;

                    baz = 25;
                }
```
would previously produce `TyDiagnosticHelpKind::NotMutatingRefThroughDeref` and now produces `TyDiagnosticHelpKind::ImmutableBinding`.

**Review by NotAFlyingGoose — APPROVED** [review]
I'll probably remove `get_range_for_expr` in a later commit since it's no longer being used, but it looks all good to me. Thank you 👍
